name: Auth Service Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Check build folder
        run: ls -la

      - name: check inside dist
        run: ls dist/

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: checking
        uses: ls

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ vars.SERVER_KEY }}
          source: "dist"
          target: "/var/www/myapp"
