name: Auth Service Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Install cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
          sudo mv cloudflared /usr/local/bin/cloudflared
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run deployment over Cloudflare SSH
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ProxyCommand="cloudflared access ssh --hostname ssh.vib3ly.shop" nitesh@ssh.vib3ly.shop

            echo "Changing directory..."
            cd /home/nitesh/Desktop/vibely/backend/Authetication

            echo "Checking out staging branch..."
            git checkout staging
            git pull origin staging

            echo "Installing dependencies..."
            npm i

            echo "Building project..."
            npm run build

            echo "Reloading PM2..."
            pm2 reload authentication
          EOF
